### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by xackery** [EQMacEmu/quests#2] opened 2023-08-02 01:55 UTC
https://github.com/EQMacEmu/quests/blob/main/rivervale/Fiddy_Bobick.lua#L8
wp should be e.wp

ssratemplate/encounters/ArchTormentor.lua line 6+ call_iksar_bow(e); Undefined global `e`.
ssratemplate/encounters/PrimeEducator.lua line function IksarShoutBow() then calls call_iksar_bow(e);  Undefined global `e`.
e isn't even used, so can likely be safely removed as an arg

qrg/Larsk_Juton.lua line 68 math.random(2137,2172,9006,5033) This function expects a maximum of 2 argument(s) but instead it is receiving 4. https://fxcodebase.com/documents/IndicoreSDK/lua/pdf-math.random.html

This one may be causing this NPC to spawn items from ID range 2137 to 2173

poair/encounters/Wind.lua 81 has RepopIsland(ISLAND_SPAWNIDS);, , but function RepopIsland() has no arg support

jaggedpine/encounters/jpfwar.lua Undefined global `spn`.

poearth/encounters/DustRing.lua line 59: local triKills, bossWave = 0, 0, 0; Only has 2 variables, but you set 3 values.

eq.register_npc_event("TortureTrial", Event.death, WRAITH_TYPE, WraithDeath); Undefined global `WraithDeath`.

This one I'm debating if truly an issue:
Annotations specify that a return value is required here.
```lua
function SortValidPlayerList()
	table.sort(validPlayers, function(a, b) if ( a[2] < b[2] ) then return true; end end );
end
```
---
potimeb/encounters/Phase3.lua
for _, typ in ipairs(BOSSES) do
Undefined global `BOSSES`.
---
potimeb/encounters/Phase6.lua : 259
eq.depop_all(corpseType);
Undefined global `corpseType`.
---
e.self:Emote("grins and regards you with malice.  'Your time will come.",11);
I don't think emote has support for the ,11 ending
---
potimeb/223077's  function Unpacket(s, numberize, returnTable) is full of warnings but it's because there's no explicit returns defined, I can't lint it easily

**Comment by regneq** [comment] 2023-08-02 02:50
> https://github.com/EQMacEmu/quests/blob/main/rivervale/Fiddy_Bobick.lua#L8
wp should be e.wp

> ssratemplate/encounters/ArchTormentor.lua line 6+ call_iksar_bow(e); Undefined global e.
ssratemplate/encounters/PrimeEducator.lua line function IksarShoutBow() then calls call_iksar_bow(e); Undefined global e.
e isn't even used, so can likely be safely removed as an arg

> qrg/Larsk_Juton.lua line 68 math.random(2137,2172,9006,5033) This function expects a maximum of 2 argument(s) but instead it is receiving 4. https://fxcodebase.com/documents/IndicoreSDK/lua/pdf-math.random.html

These above should be fixed.

> jaggedpine/encounters/jpfwar.lua Undefined global spn.

This is used in a function to pass the paramenter to another function:
`function GnollSpawnLocation(spn)`   working as intended.

**Comment by Torven** [comment] 2023-08-06 02:59
I ironed out what was brought up for my scripts, but the sorting function and the unpack function are fine.  Lua is dynamically typed; a function may return different types and this isn't abnormal or wrong.  Built-in Lua functions do this.

**Comment by xackery** [comment] 2023-08-06 10:47
> I ironed out what was brought up for my scripts, but the sorting function and the unpack function are fine. Lua is dynamically typed; a function may return different types and this isn't abnormal or wrong. Built-in Lua functions do this.

Yep, these are just warnings with my linter is all. The linter is a lot more rigid than what lua offers, they're more just for consideration than truly needing to be changed in any way.

I think this can be closed?

**Closed as completed** 2023-08-06 14:43 UTC
